### ISSUE TITLE
[Bug]: Select component is not triggering the livewire change event

### ISSUE THREAD

**Issue by dougkusanagi** [yungifez/artisan-ui#10]
### What happened?

The <x-aui::select> component is not working with the `wire:model.change="my_livewire_prop"`

### How to reproduce the bug

This code does not trigger the wire:model.change event to update the category_id prop of the livewire component.

```php
<x-aui::select class="w-72" wire:model.change="category_id">
    <option value="">- All Categories</option>

    @foreach ($categories as $category)
        <option value="{{ $category->id }}">{{ $category->name }}</option>
    @endforeach
</x-aui::select>
``

But the native version works fine.

```php
<x-aui::native-select class="w-72" wire:model.change="category_id">
    <option value="">- All Categories</option>

    @foreach ($categories as $category)
        <option value="{{ $category->id }}">{{ $category->name }}</option>
    @endforeach
</x-aui::native-select>
```

### Package Version

^0.0.2

### PHP Version

8.3.11

### Laravel Version

^11.9

### Which operating systems does with happen with?

Windows

**Comment by yungifez** [comment]
Thanks for the report, I'll look onto this

**Comment by yungifez** [comment]
This should now be fixed, thanks for the bug report

**Comment by dougkusanagi** [comment]
Thank you!

**Comment by yungifez** [comment]
Can I ask if you are willing to also test on custom elements like the switch

Would be greatly appreciated

**Comment by dougkusanagi** [comment]
I'll probably use the switch component in this same lil project i'm doing. Just don't know when, if i find a problem i'll open an issue. If thats what you mean with test.

**Comment by yungifez** [comment]
Yeah that's fine
