### ISSUE TITLE
[Bug]: The dropdown menu gets clipped by the viewport

### ISSUE THREAD

**Issue by alnahian2003** [yungifez/artisan-ui#11]
### What happened?

![image](https://github.com/user-attachments/assets/e3c2af60-7e34-442a-857f-270aa6acbaf1)
While trying the demo on the website, I noticed that in the **dropdown** example, the **dropdown menu** opens nicely in the normal viewport but gets clipped in small viewports, such as mobile devices.
![image](https://github.com/user-attachments/assets/5a227e2a-4f95-4b0c-ac35-c95ef358c103)

### How to reproduce the bug

Switch to a small viewport or zoom the window to about 125% in your browser to reproduce the bug.

### Package Version

0.02

### PHP Version

8.3.11

### Laravel Version

11.x

### Which operating systems does with happen with?

Windows

**Comment by yungifez** [comment]
Unfortunately I think this is the behaviour of the shadcn dropdown too 


It's as a result of anchoring

In reality, I doubt people would have such big dropdowns.

I also plan on reducing the padding of the button for this very situation

**Comment by yungifez** [comment]
Unfortunately I think this is the behaviour of the shadcn dropdown too 


It's as a result of anchoring

In reality, I doubt people would have such big dropdowns.

I also plan on reducing the padding of the button for this very situation
